// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkiECLMrhGmViMjcdicP5AHM72nmmWAKw',
    appId: '1:333847671318:web:a53f38d1e755516541fb37',
    messagingSenderId: '333847671318',
    projectId: 'squadup-702ba',
    authDomain: 'squadup-702ba.firebaseapp.com',
    storageBucket: 'squadup-702ba.appspot.com',
    measurementId: 'G-PQXBMBBGBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dLMF_fs5hUH4pdEkxfEaWeMq-IRdRUc',
    appId: '1:333847671318:android:c381fb3fff0e39e341fb37',
    messagingSenderId: '333847671318',
    projectId: 'squadup-702ba',
    storageBucket: 'squadup-702ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ISd5dn-RHcT27oyH0GC5Z01SFydSW4E',
    appId: '1:333847671318:ios:f8bb10efbdd98cca41fb37',
    messagingSenderId: '333847671318',
    projectId: 'squadup-702ba',
    storageBucket: 'squadup-702ba.appspot.com',
    iosBundleId: 'com.example.squadUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ISd5dn-RHcT27oyH0GC5Z01SFydSW4E',
    appId: '1:333847671318:ios:f8bb10efbdd98cca41fb37',
    messagingSenderId: '333847671318',
    projectId: 'squadup-702ba',
    storageBucket: 'squadup-702ba.appspot.com',
    iosBundleId: 'com.example.squadUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkiECLMrhGmViMjcdicP5AHM72nmmWAKw',
    appId: '1:333847671318:web:76867b6502e6199e41fb37',
    messagingSenderId: '333847671318',
    projectId: 'squadup-702ba',
    authDomain: 'squadup-702ba.firebaseapp.com',
    storageBucket: 'squadup-702ba.appspot.com',
    measurementId: 'G-Q5TJL57LNZ',
  );
}
